# 1.내장함수

## 1)문자열 내장함수

In [1]:
# count() : 문자열 내의 특정 문자 개수 세기
str = "python programming"
str.count('p')

2

In [2]:
# join() : 문자열 삽입
"/".join("python progmraming")

'p/y/t/h/o/n/ /p/r/o/g/m/r/a/m/i/n/g'

In [3]:
# firnd() : 찾는 문자열이 처음 나온 인덱스 반환
str = "python programming"
str.find('m')

13

In [6]:
# upper() : 소문자를 대문자로 변환
str = "python programming"
str = str.upper()
print(str)

# lower() : 대분자를 소문자로 변환
str = str.lower()
print(str)

PYTHON PROGRAMMING
python programming


In [8]:
# repace() : 문자열 내의 특정 값을 다른 값으로 치환
str="Python Programming"
str.replace("Python", "Java") 

'Java Programming'

In [9]:
# split() : 공백 또는 특정 문자를 구분자로 문자열 분리
str = "Python Programming"
str.split()

['Python', 'Programming']

## 2) 시퀀스 자료형의 내장함수

### (1)리스트 내장함수


In [18]:
arr = ['a', 'b', 'c']

# append() : 리스트 맨 뒤에 추가
arr.append('d')
print(arr)

# insert() : 원하는 인덱스에 추가
arr.insert(1, 'a')
print(arr)

# 리스트 원소 수정
arr[1] = 'f'
print(arr)

# 인덱스 번호로 리스트 원소 삭제
del arr[1]
print(arr)

# 요소로 리스트 원소 삭제(가장 앞에 있는 것 하나만 삭제)
arr.remove('b')
print(arr)

# index() : 해당 원소가 위치한 인덱스 값 반환
# sort() : 정렬
# reverse() : 역순으로 배열
# count() : 해당 원소 포함된 갯수 반환

['a', 'b', 'c', 'd']
['a', 'a', 'b', 'c', 'd']
['a', 'f', 'b', 'c', 'd']
['a', 'b', 'c', 'd']
['a', 'c', 'd']


### (2)튜플과 딕셔너리의 내장함수

In [19]:
dic1 = {1:'a', 2:'b', 3:'c'}
dic2 = {'name':'python', 'age':30, 'job':'programming'}

# keys() : key만 모아서 dict_keys 객체로 반환
print(dic1.keys())

# values() : value만 모아서 dict_values 객체로 반환
print(dic2.values())

# items() : key와 value를 튜플로 묶은 값들을 모아서 dict_items 객체로 반환
print(dic1.items())

# in : key가 딕셔너리 안에 있는지 조사
if 'age' in dic2:
# get() : key에 대응되는 value를 반환
    print(dic2.get('age'))

  

dict_keys([1, 2, 3])
dict_values(['python', 30, 'programming'])
dict_items([(1, 'a'), (2, 'b'), (3, 'c')])
30


# 2.넘파이

In [34]:
import numpy as np

# array() : 리스트, 튜플 등 데이터를 이용하여 ndarray객체 생성
arr1 = np.array([1,2,3,4,5])
print(arr1)

# random.randn(행,열) : 가우시안 정규분포를 갖는 난수 생성, 숫자 하나만 적으면 1행 n열 
arr2 = np.random.randn(2,3)
print(arr2)

# zeros((행,열)) : narray 객체 생성후 0으로 초기화
# ones() : narray 객체 생성 후 1로 초기화
arr0 = np.zeros((2,3))
print(arr0)

# arange(이상,미만,간격) : 내장함수 range()와 동일한 기능
arr3 = np.arange(1,21,1)
print(arr3)

# reshape(행,열) : narray의 차원을 재구성
arr4=arr3.reshape(2,10)
print(arr4)

# where : 조건식에 따라 배열의 요소 값을 특정 값으로 변경
arr5 = np.array([[5,7,9],
               [-7,-6,19],
               [6,9,11]])
print(arr5>5)

m_count = (arr5<0).sum()
print(m_count)

arr6 = np.where(arr5<0, 0, arr5)    # arr5의 원소가 0보다 작으면 0으로 변경, 그렇지 않으면 arr5값 대입
print(arr6)
# sort() : 배열 오름차순 정렬
# sum(), mean(), max(), min() : 집계 함수
# argmax() : 열 또는 행의 요소 중 최대값을 가지는 요소의 인덱스 반환
# argmin() : 열 또는 행의 요소 중 최소값을 가지는 요소의 인덱스 반환

[1 2 3 4 5]
[[ 1.04392537  1.50300345  0.082844  ]
 [ 1.21109755  1.34862366 -1.33074978]]
[[0. 0. 0.]
 [0. 0. 0.]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
[[False  True  True]
 [False False  True]
 [ True  True  True]]
2
[[ 5  7  9]
 [ 0  0 19]
 [ 6  9 11]]


# 3. 판다스

## 1) 시리즈

In [40]:
import pandas as pd

# 시리즈 객체 생성
sr1 = pd.Series([10, 30, 20, 40, 60])
print(sr1)

# 시리즈 객체의 값과 인덱스 확인
print(sr1.values)
print(sr1.index)
print(sr1[2])

# 시리즈 객체 인덱스 설정하기
sr1 = pd.Series([10, 30, 20, 40, 60], index=['a', 'b', 'c', 'd', 'e'])
print(sr1)
print(sr1[0], sr1['a'])

# 원소 선택
print(sr1[[1,2]])
print(sr1[['a','c']])


0    10
1    30
2    20
3    40
4    60
dtype: int64
[10 30 20 40 60]
RangeIndex(start=0, stop=5, step=1)
20
a    10
b    30
c    20
d    40
e    60
dtype: int64
10 10
b    30
c    20
dtype: int64
a    10
c    20
dtype: int64


## 2) 데이터프레임

In [45]:
# 데이터프레임 객체 생성
df1 = pd.DataFrame([[10, 20, 30],
                    [40, 50, 60]])
print(df1)

# 딕셔너리를 이용한 데이터프레임 생성
dic1 = {
    'fruit' : ['사과', '배', '감', '귤', '바나나'],
    'price' : [100, 200, 10, 50, 200],
    'qty' : [10, 25, 30, 20, 15]
}
df2 = pd.DataFrame(dic1)
print(df2)

# 데이터프레임 객체의 인덱스/열이름 정하기
df3 = pd.DataFrame(dic1, index=['a', 'b', 'c', 'd', 'e'])
print(df3)

# rename() : 생성된 데이터프레임의 인덱스와 칼럼명을 변경할 때 사용, inplace=Ture 옵션 있음
df3.rename(columns = {'fruit':'과일', 'price':'가격', 'qty':'수량'}, inplace=True)
df3.rename(index = {'a':'01', 'b':'02', 'c':'03', 'd':'04', 'e':'05'}, inplace=True)
print(df3)

    0   1   2
0  10  20  30
1  40  50  60
  fruit  price  qty
0    사과    100   10
1     배    200   25
2     감     10   30
3     귤     50   20
4   바나나    200   15
  fruit  price  qty
a    사과    100   10
b     배    200   25
c     감     10   30
d     귤     50   20
e   바나나    200   15
     과일   가격  수량
01   사과  100  10
02    배  200  25
03    감   10  30
04    귤   50  20
05  바나나  200  15


## 3) 데이터 살펴보기

In [47]:
# CSV 파일 로드
df1 = pd.read_csv('./csv/df_sample.csv')
df1

학번  중간  기말  리포트  퀴즈
0  S01  90  95   20  20
1  S02  82  83   18  18
2  S03  80  78   18  18
3  S04  78  75   10  10
4  S05  93  91   12  12
5  S06  71  75   16  16
6  S07  60  80   18  18
7  S08  72  65   14  14
8  S09  65  65   14  14
9  S10  85  78   10  10

In [60]:
# 데이터 셋 일부분만 보기
print(df1.head(5))  
print(df1.tail(5))



    학번  중간  기말  리포트  퀴즈
0  S01  90  95   20  20
1  S02  82  83   18  18
2  S03  80  78   18  18
3  S04  78  75   10  10
4  S05  93  91   12  12
    학번  중간  기말  리포트  퀴즈
5  S06  71  75   16  16
6  S07  60  80   18  18
7  S08  72  65   14  14
8  S09  65  65   14  14
9  S10  85  78   10  10
(10, 5)


In [62]:
# 데이터 요약 정보 확인하기
print(df1.shape)

# 데이터 개수 세기
print(df1.count())

(10, 5)
학번     10
중간     10
기말     10
리포트    10
퀴즈     10
dtype: int64


In [65]:
# 데이터프레임 기본 정보 확인하기
print(df1.info)

# describe(include='all) : 데이터프레임 기술 통계 확인하기
print(df1.describe(include='all'))

# corr() : 데이터프레임 상관계수 확인하기
print(df1.corr())

<bound method DataFrame.info of     학번  중간  기말  리포트  퀴즈
0  S01  90  95   20  20
1  S02  82  83   18  18
2  S03  80  78   18  18
3  S04  78  75   10  10
4  S05  93  91   12  12
5  S06  71  75   16  16
6  S07  60  80   18  18
7  S08  72  65   14  14
8  S09  65  65   14  14
9  S10  85  78   10  10>
         학번         중간         기말        리포트         퀴즈
count    10  10.000000  10.000000  10.000000  10.000000
unique   10        NaN        NaN        NaN        NaN
top     S01        NaN        NaN        NaN        NaN
freq      1        NaN        NaN        NaN        NaN
mean    NaN  77.600000  78.500000  15.000000  15.000000
std     NaN  10.616549   9.663793   3.559026   3.559026
min     NaN  60.000000  65.000000  10.000000  10.000000
25%     NaN  71.250000  75.000000  12.500000  12.500000
50%     NaN  79.000000  78.000000  15.000000  15.000000
75%     NaN  84.250000  82.250000  18.000000  18.000000
max     NaN  93.000000  95.000000  20.000000  20.000000
           중간        기말       리

/var/folders/12/gbtc492d66jfrlnvrtjqzy780000gn/T/ipykernel_2261/2337984125.py:8: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  print(df1.corr())


In [71]:
# 데이터프레임에 통계함수 적용하기
print("평균 :")
print(df1['중간'].mean())
print(df1[['중간','기말']].mean())

# 열의 표준편차와 분산
print('표준편차 :')
# std() : 표준편차 구하는 메소드
print(df1[['중간','기말']].std())   
print('분산 :')
# var() : 분산 구하는 메소드
print(df1[['중간','기말']].var())   


평균 :
77.6
중간    77.6
기말    78.5
dtype: float64
표준편차 :
중간    10.616549
기말     9.663793
dtype: float64
분산 :
중간    112.711111
기말     93.388889
dtype: float64


In [72]:
# value_counts() : 지정 열에 퐇마되어 있는 고유한 값의 개수 세기
df1['퀴즈'].value_counts()

18    3
10    2
14    2
20    1
12    1
16    1
Name: 퀴즈, dtype: int64

In [84]:
# 열값 읽어와서 인덱스 적용 (컬럼에 남아있음)
df1 = pd.read_csv('./csv/df_sample.csv')
df1.index = df1['학번']
print(df1)

# set_index() : 칼럼에 남지 않음
df1 = pd.read_csv('./csv/df_sample.csv')
df1.set_index('학번', inplace=True)
print(df1)

# sort_index(ascending=False) : 내림차순 정렬
df2 = df1.sort_index(ascending=False)
print(df2)

      학번  중간  기말  리포트  퀴즈
학번                       
S01  S01  90  95   20  20
S02  S02  82  83   18  18
S03  S03  80  78   18  18
S04  S04  78  75   10  10
S05  S05  93  91   12  12
S06  S06  71  75   16  16
S07  S07  60  80   18  18
S08  S08  72  65   14  14
S09  S09  65  65   14  14
S10  S10  85  78   10  10
     중간  기말  리포트  퀴즈
학번                  
S01  90  95   20  20
S02  82  83   18  18
S03  80  78   18  18
S04  78  75   10  10
S05  93  91   12  12
S06  71  75   16  16
S07  60  80   18  18
S08  72  65   14  14
S09  65  65   14  14
S10  85  78   10  10
     중간  기말  리포트  퀴즈
학번                  
S10  85  78   10  10
S09  65  65   14  14
S08  72  65   14  14
S07  60  80   18  18
S06  71  75   16  16
S05  93  91   12  12
S04  78  75   10  10
S03  80  78   18  18
S02  82  83   18  18
S01  90  95   20  20


In [86]:
# sort_values() :  데이터프레임 정렬(특정 열 기준)
df3 = df1.sort_values(by='기말', ascending=True)
df3

중간  기말  리포트  퀴즈
학번                  
S08  72  65   14  14
S09  65  65   14  14
S04  78  75   10  10
S06  71  75   16  16
S03  80  78   18  18
S10  85  78   10  10
S07  60  80   18  18
S02  82  83   18  18
S05  93  91   12  12
S01  90  95   20  20

## 4) 데이터 전처리

In [122]:
df = pd.read_csv('./csv/df_sample.csv')
df.index = df1['학번']

df["합계"] = df["중간"] + df["기말"]
df

학번  중간  기말  리포트  퀴즈   합계
학번                            
S01  S01  90  95   20  20  185
S02  S02  82  83   18  18  165
S03  S03  80  78   18  18  158
S04  S04  78  75   10  10  153
S05  S05  93  91   12  12  184
S06  S06  71  75   16  16  146
S07  S07  60  80   18  18  140
S08  S08  72  65   14  14  137
S09  S09  65  65   14  14  130
S10  S10  85  78   10  10  163

### (1) 표준화

In [123]:
# 표준화 : 각 데이터 값들이 평균을 기준으로 얼마나 떨어져 있는지 표현하는 값
## Z-score구하기  z = (x - mean()) / std()
import numpy as np
mid_avg = np.mean(df["중간"]) 
mid_std = np.std(df["중간"])
df['중간_Z점수'] = (df["중간"] - mid_avg) / mid_std
df.head()


학번  중간  기말  리포트  퀴즈   합계    중간_Z점수
학번                                      
S01  S01  90  95   20  20  185  1.231167
S02  S02  82  83   18  18  165  0.436866
S03  S03  80  78   18  18  158  0.238290
S04  S04  78  75   10  10  153  0.039715
S05  S05  93  91   12  12  184  1.529030

### (2) 정규화

In [124]:
# 정규화 : 정규화는 데이터의 범위를 0과 1사이로 변환하여 데이터의 분포를 조정하는 것
## (x - min()) / (max() - min()), MinMaxScaler(), minmax_scale()
fin_min = np.min(df["기말"])
fin_max = np.max(df["기말"])
df["기말_정규화"] = (df['기말'] - fin_min) / (fin_max - fin_min)
df.head()

학번  중간  기말  리포트  퀴즈   합계    중간_Z점수    기말_정규화
학번                                                
S01  S01  90  95   20  20  185  1.231167  1.000000
S02  S02  82  83   18  18  165  0.436866  0.600000
S03  S03  80  78   18  18  158  0.238290  0.433333
S04  S04  78  75   10  10  153  0.039715  0.333333
S05  S05  93  91   12  12  184  1.529030  0.866667

In [125]:
x = ["1반", '1반', '1반', '2반', '2반', '2반', '3반', '3반', '3반', '3반']
df['cls'] = x

### (3) 데이터 요약

In [126]:
# 데이터 요약
# groupby() : 특정 열을 기준으로 데이터를 그룹화하고 집계함수를 적용
df_cls_grp = df.groupby(df['cls'])
df_cls_grp.mean()

/var/folders/12/gbtc492d66jfrlnvrtjqzy780000gn/T/ipykernel_2261/2451922337.py:4: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_cls_grp.mean()


중간         기말        리포트         퀴즈          합계    중간_Z점수  \
cls                                                                     
1반   84.000000  85.333333  18.666667  18.666667  169.333333  0.635441   
2반   80.666667  80.333333  12.666667  12.666667  161.000000  0.304482   
3반   70.500000  72.000000  14.000000  14.000000  142.500000 -0.704943   

       기말_정규화  
cls            
1반   0.677778  
2반   0.511111  
3반   0.233333

In [127]:
# groupby.count() : 각 범주별 빈도수 계산
df['중간'].groupby(df['cls']).count()

cls
1반    3
2반    3
3반    4
Name: 중간, dtype: int64

In [128]:
# apply() : 데이터의 행 또는 열 방향으로 중진 함수를 한 번에 적용
df["퀴즈"].apply(np.sqrt)

학번
S01    4.472136
S02    4.242641
S03    4.242641
S04    3.162278
S05    3.464102
S06    4.000000
S07    4.242641
S08    3.741657
S09    3.741657
S10    3.162278
Name: 퀴즈, dtype: float64

### (4) 결측값 처리

In [129]:
# 결측값 식별
## info() : 정보로 결측치 파악
x = [14, 15, 13, 14, None, None, 19, 11, 12, 18]
df['토론'] = x

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, S01 to S10
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   학번      10 non-null     object 
 1   중간      10 non-null     int64  
 2   기말      10 non-null     int64  
 3   리포트     10 non-null     int64  
 4   퀴즈      10 non-null     int64  
 5   합계      10 non-null     int64  
 6   중간_Z점수  10 non-null     float64
 7   기말_정규화  10 non-null     float64
 8   cls     10 non-null     object 
 9   토론      8 non-null      float64
dtypes: float64(3), int64(5), object(2)
memory usage: 1.2+ KB


In [130]:
## isnull() : 데이터가 없으면 Ture, 있으면 False
df.isnull()

학번     중간     기말    리포트     퀴즈     합계  중간_Z점수  기말_정규화    cls     토론
학번                                                                         
S01  False  False  False  False  False  False   False   False  False  False
S02  False  False  False  False  False  False   False   False  False  False
S03  False  False  False  False  False  False   False   False  False  False
S04  False  False  False  False  False  False   False   False  False  False
S05  False  False  False  False  False  False   False   False  False   True
S06  False  False  False  False  False  False   False   False  False   True
S07  False  False  False  False  False  False   False   False  False  False
S08  False  False  False  False  False  False   False   False  False  False
S09  False  False  False  False  False  False   False   False  False  False
S10  False  False  False  False  False  False   False   False  False  False

In [131]:
## notnull() : 데이터가 있으면 True, 없으면 False
df.notnull()

학번    중간    기말   리포트    퀴즈    합계  중간_Z점수  기말_정규화   cls     토론
학번                                                                  
S01  True  True  True  True  True  True    True    True  True   True
S02  True  True  True  True  True  True    True    True  True   True
S03  True  True  True  True  True  True    True    True  True   True
S04  True  True  True  True  True  True    True    True  True   True
S05  True  True  True  True  True  True    True    True  True  False
S06  True  True  True  True  True  True    True    True  True  False
S07  True  True  True  True  True  True    True    True  True   True
S08  True  True  True  True  True  True    True    True  True   True
S09  True  True  True  True  True  True    True    True  True   True
S10  True  True  True  True  True  True    True    True  True   True

In [132]:
# 결측값 대치
## dropna() : 결측값이 있는 행 제거(완전분석법)
df_new = df.dropna(axis=0)      # axis=1이면 열을 제거
df_new = df["토론"].dropna()     # '토론'열에서 결측값 제거
df_new


학번
S01    14.0
S02    15.0
S03    13.0
S04    14.0
S07    19.0
S08    11.0
S09    12.0
S10    18.0
Name: 토론, dtype: float64

In [118]:
## fillna() : 결측값을 지정한 겂으로 대체(평균대치법)
d_mean = df['토론'].mean()
df['토론'].fillna(d_mean, inplace=True)
df["토론"]

학번
S01    14.0
S02    15.0
S03    13.0
S04    14.0
S05    14.5
S06    14.5
S07    19.0
S08    11.0
S09    12.0
S10    18.0
Name: 토론, dtype: float64

### (5) 이상값 처리

In [133]:
# 이상값 식별
## quantile(p) : 사분위수 함수 
## p의 값 : 0은 최소값, 1은 최대값, 0,25는 1사분위수, 0.5는 2사분위수, 0.75는 3사분위수
## 사분위범위 : 3사분위수 - 1사분위수

# 이상값 판별 : (1사분위수 - 1.5*사분위범위)보다 작거나 (3사분위수 + 1.5사분위범위)보다 큰 수
df_1QR = df['기말'].quantile(0.25)  # 1사분위수
print(df_1QR)
df_3QR = df['기말'].quantile(0.75)  # 3사분위수
print(df_3QR)
df_IQR = df_3QR - df_1QR           # 사분위범위
print(df_IQR)

# 이상값 제거

75.0
82.25
7.25
