PART 03 R 분석

> CHAPTER 01 R 프로그래밍
> >SECTION 01 R 프로그래밍 기초
> > >**02 변수, 데이터타입, 연산자**

In [1]:
a <- 1    # 변수 a의 값은 1
a         # a를 그대로 실행하면 a의 값인 1이 출력

[1] 1

In [ ]:
b <- 5    # 변수 b의 값은 5
a <- b    # 변수 a에 변수 b의 값을 할당
a         # a의 실행 결과로 5가 출력

[1] 5

In [ ]:
a <- 1        # a, b는 숫자형 변수
b <- 1.5
a             # a에는 정수 1
b             # b에는 실수 1.5

[1] 1

[1] 1.5

In [ ]:
a <- 1            # a에 1을 할당
b <- a            # b에는 a의 값을 할당
x <- c(b, 2, 7)   # b값과 2, 7을 결합하여 변수 x에 할당
a
b
x

[1] 1

[1] 1

[1] 1 2 7

In [ ]:
a = 10
b = 5
c = 3

# ;을 사용해서 2개 이상의 문장을 한 줄에 적을 수 있다.
a+b; a-b; a*b; a/b
a^c; a%/%c; a%%c      # 10^3 → 1000, 10%/%3 → 3(몫), 10%%3 → 1(나머지)

[1] 15

[1] 5

[1] 50

[1] 2

[1] 1000

[1] 3

[1] 1

In [ ]:
str1 <- "R" # 문자열 str1에 R
str2 <- "Programming" # 문자열 str2에 Programming
str1
str2

[1] "R"

[1] "Programming"

In [ ]:
# 여러 개의 문자로 구성된 변수 생성
str3 <- c('a','b','c')
str3
str4 <- c("R","Programming")
str4

[1] "a" "b" "c"

[1] "R"           "Programming"

In [ ]:
str1 <- "R"
str2 <- "Programming"
str3 <- paste(str1, str2)             # str1과 str2를 합쳐서 str3에 저장
str3
str4 <- c("a","b","c")
str5 <- paste(str4, collapse=" ")   # str4에 포함된 3개 문자(열)를 공백과 함께 str5에 저장
str5

[1] "R Programming"

[1] "a b c"

In [ ]:
str1 <- '2022-04-09'    # 문자형
str2 <- '2022-06-25'    # 문자형
x <- as.Date(str1)        # 날짜형으로 변환
y <- as.Date(str2)        # 날짜형으로 변환
y - x                     # 날짜 연산 (날짜형은 산술연산이 가능)

Time difference of 77 days

In [ ]:
x <- TRUE
y <- FALSE

x & y         # 논리곱 TRUE & FALSE → FALSE
x | y         # 논리합 TRUE | FALSE → TRUE
!y            # 부정 !FALSE → TRUE

[1] FALSE

[1] TRUE

[1] TRUE

>>>**03 벡터, 행렬, 배열**

In [ ]:
x1 <- c(1,2,3)    # 벡터 x1 생성
x1                # x1 값 출력 : 숫자형
x2 <- c("a","b","c","d")  # 벡터 x2 생성
x2                                # x2 값 출력 : 문자형
x3 <- c(1,2,"a","b")    # 벡터 x3 생성
x3                          # x3 값 출력 : 문자형

[1] 1 2 3

[1] "a" "b" "c" "d"

[1] "1" "2" "a" "b"

In [ ]:
x1 <- c(1,2,3)      # 벡터 x1 생성
x2 <- rep(x1, 3)    # x1을 3회 반복
x2
x3 <- seq(1,10,2)    # 1부터 10까지 2씩 증가하는 수열 생성
x3

[1] 1 2 3 1 2 3 1 2 3

[1] 1 3 5 7 9

In [ ]:
x <- c(1:5)    # 1부터 5까지 숫자로 구성된 벡터 생성
x[3]           # 벡터 x의 3번째 원소 출력 => 3
x[c(3,5)]      # 벡터 x의 3번째, 5번째 원소 출력
x[1:3]         # 벡터 x의 1~3번째 원소 출력
x[-2]          # 벡터 x의 원소 중 2번째 원소를 제외하고 출력
x[x >= 4]      # 벡터 x의 원소 중 4보다 큰 값만 출력

[1] 3

[1] 3 5

[1] 1 2 3

[1] 1 3 4 5

[1] 4 5

In [ ]:
x <- c(100, 200, 300)
names(x) <- c("aaa","bbb","ccc")    # 벡터 x의 각 원소 위치에 이름을 부여

x["bbb"]                            # 이름을 이용하여 벡터 x의 값을 출력
names(x)                            # 벡터 x에 부여된 이름 전체 출력

bbb 
200

[1] "aaa" "bbb" "ccc"

In [ ]:
x1 <- c(100,200,300,400)    # 벡터 x1(100,200,300,400) 생성
x2 <- c(10,20,30,40)        # 벡터 x2(10,20,30,40) 생성
x3 <- c(10,20)              # 벡터 x2(10,20) 생성

x1+x2       # x1과 x2의 대응되는 원소를 더함 => (110,220,330,440)
x1-x2       # x1에서 x2의 대응되는 원소를 뺌 => (90,180,290,380)
x1*x2       # x1과 x2의 대응되는 원소를 곱합

x1+x3       # 원소수가 작은 벡터는 기존의 원소가 반복되어 채워짐
x1/x3       # 즉, x3가 (10,20)에서 (10,20,10,20)으로 확장됨

[1] 110 220 330 440

[1]  90 180 270 360

[1]  1000  4000  9000 16000

[1] 110 220 310 420

[1] 10 10 30 20

In [ ]:
x1 <- c(10,20,30,40)    # 벡터 x1(10,20,30) 생성
x2 <- c(30,40,50,60)    # 벡터 x2(40,50,60) 생성
x3 <- c(40,30,20,10)    # 벡터 x3(40,50,60) 생성

union(x1,x2)      # 합집합
intersect(x1,x2)  # 교집합
setdiff(x1,x2)    # 차집합 x1-x2
setequal(x1,x2)   # x1과 x2가 동일하면 TRUE, 아니면 FALSE 반환
setequal(x1,x3)   # x1과 x3는 동일집합(원소의 순서는 무관함)

[1] 10 20 30 40 50 60

[1] 30 40

[1] 10 20

[1] FALSE

[1] TRUE

In [ ]:
x <- c(10,20,30,40,50)    # 벡터 x 생성

sum(x)        # x의 합계
mean(x)       # x의 평균
sd(x)         # x의 표준편차
var(x)        # x의 분산

[1] 150

[1] 30

[1] 15.81139

[1] 250

In [ ]:
x <- c(1:20)            # 1부터 20까지 원소를 갖는 벡터생성
x <- matrix(x, 5, 4)    # 벡터 x를 5X4 행렬로 변환
x                       # 행렬 x출력

[,1] [,2] [,3] [,4]
[1,] 1     6   11   16  
[2,] 2     7   12   17  
[3,] 3     8   13   18  
[4,] 4     9   14   19  
[5,] 5    10   15   20

In [ ]:
x <- matrix(1:20, 5,4)    # 5X4 행렬 생성
x[1,3]                    # 1행 3열의 데이터 선택

[1] 11

In [ ]:
x[2:4, 3:4]       # 2~4행, 3~4열에 해당하는 데이터 선택

[,1] [,2]
[1,] 12   17  
[2,] 13   18  
[3,] 14   19

In [ ]:
x[-3,]            # 3행을 제외한 나머지 데이터 선택

[,1] [,2] [,3] [,4]
[1,] 1     6   11   16  
[2,] 2     7   12   17  
[3,] 4     9   14   19  
[4,] 5    10   15   20

>>>**04 데이터프레임과 리스트**

In [ ]:
# 벡터(열) 생성
x1 <- c("01","02","03","04","05")
x2 <- c("사과","배","감","귤","바나나")
x3 <- c(100,200,150,50,200)
x4 <- c(10,25,30,20,15)

# 데이터프레임 생성과 출력
df = data.frame(과일번호=x1, 과일명=x2, 가격=x3, 수량=x4)
df

과일번호 과일명 가격 수량
1 01       사과   100  10  
2 02       배     200  25  
3 03       감     150  30  
4 04       귤      50  20  
5 05       바나나 200  15

In [ ]:
str(df)

'data.frame':	5 obs. of  4 variables:
 $ 과일번호: chr  "01" "02" "03" "04" ...
 $ 과일명  : chr  "사과" "배" "감" "귤" ...
 $ 가격    : num  100 200 150 50 200
 $ 수량    : num  10 25 30 20 15


In [ ]:
df[2, ]

과일번호 과일명 가격 수량
2 02       배     200  25

In [ ]:
df[ , "과일명"]

[1] "사과"   "배"     "감"     "귤"     "바나나"

In [ ]:
df$과일명 # df[ , "과일명"]과 동일

[1] "사과"   "배"     "감"     "귤"     "바나나"

In [ ]:
head(df, n=2)   # 상위 2개 행 선택

과일번호 과일명 가격 수량
1 01       사과   100  10  
2 02       배     200  25

In [ ]:
tail(df, n=2)   # 하위 2개 행 선택

과일번호 과일명 가격 수량
4 04       귤      50  20  
5 05       바나나 200  15

In [ ]:
subset(df, 가격 >= 150)    # 가격이 150 이상인 행 선택

과일번호 과일명 가격 수량
2 02       배     200  25  
3 03       감     150  30  
5 05       바나나 200  15

In [ ]:
subset(df, 가격 >= 150, select=c("과일번호", "과일명"))

과일번호 과일명
2 02       배    
3 03       감    
5 05       바나나

In [ ]:
df1 <- head(df, n=2)    # 상위 2개 행 선택
df2 <- tail(df, n=2)    # 하위 2개 행 선택
rbind(df1,df2)          # 행 결합

과일번호 과일명 가격 수량
1 01       사과   100  10  
2 02       배     200  25  
4 04       귤      50  20  
5 05       바나나 200  15

In [ ]:
cbind(df1,df2)       # 열 결합

과일번호 과일명 가격 수량 과일번호 과일명 가격 수량
1 01       사과   100  10   04       귤      50  20  
2 02       배     200  25   05       바나나 200  15

In [ ]:
x <- c("사과","배","감","귤","바나나")      # 벡터 x 생성

y1 <- c(10,20,30,40,50)
y2 <- c(10,20,30,40,50)
df = data.frame(y1, y2)       # 데이터프레임 생성

lst1 <- list(x, df)           # 리스트 생성
lst1                          # x와 df의 값이 각각 출력된다.

[[1]]
[1] "사과"   "배"     "감"     "귤"     "바나나"

[[2]]
  y1 y2
1 10 10
2 20 20
3 30 30
4 40 40
5 50 50

In [ ]:
x <- c("사과","배","감","귤","바나나")    # 벡터 x 생성
y <- c(10:20)                             # 벡터 y 생성

lst1 <- list("과일"=x, "숫자"=y)      # 리스트 생성
lst1[1]                             # lst1의 첫번째 객체 x 출력
lst1$숫자                           # lst1의 "숫자" 객체인 y 출력

$과일
[1] "사과"   "배"     "감"     "귤"     "바나나"

[1] 10 11 12 13 14 15 16 17 18 19 20

>>>**05 조건문과 반복문**

In [ ]:
a <- 10

if (a > 0){                     # a>0는 참이기 때문에 if문 내의 문장을 실행
    print("a는 양의 정수입니다.")
}

[1] "a는 양의 정수입니다."


In [ ]:
a <- -10

if (a >= 0){                     # a>0는 거짓이기 때문에 else문 내의 문장을 실행
    print("a는 0보다 크거나 같습니다.")
} else {
    print("a는 0보다 작습니다.")
}

[1] "a는 0보다 작습니다."


In [ ]:
x <- c(10,20,30,40,50)

# x의 각 원소에 대해서 30이상이면 "30이상", 아니면 "30미만"을 출력
ifelse(x >= 30, "30이상", "30미만")

[1] "30미만" "30미만" "30이상" "30이상" "30이상"

In [ ]:
for(i in 1:4){
    print(i)
}

[1] 1
[1] 2
[1] 3
[1] 4


In [ ]:
x = c("a", "b", "c", "d", "e")
for(i in x){
    print(i)
}

[1] "a"
[1] "b"
[1] "c"
[1] "d"
[1] "e"


In [ ]:
for(i in 2:9){                            # i는 2부터 9까지 반복
    for (j in 1:9){                       # j는 1부터 9까지 반복
        cat(i, "*", j, "=", i*j, " ")     # 2*1=2 형태로 반복해서 출력
    }
    cat("\n")                             # 줄바꿈
}

2 * 1 = 2  2 * 2 = 4  2 * 3 = 6  2 * 4 = 8  2 * 5 = 10  2 * 6 = 12  2 * 7 = 14  2 * 8 = 16  2 * 9 = 18  
3 * 1 = 3  3 * 2 = 6  3 * 3 = 9  3 * 4 = 12  3 * 5 = 15  3 * 6 = 18  3 * 7 = 21  3 * 8 = 24  3 * 9 = 27  
4 * 1 = 4  4 * 2 = 8  4 * 3 = 12  4 * 4 = 16  4 * 5 = 20  4 * 6 = 24  4 * 7 = 28  4 * 8 = 32  4 * 9 = 36  
5 * 1 = 5  5 * 2 = 10  5 * 3 = 15  5 * 4 = 20  5 * 5 = 25  5 * 6 = 30  5 * 7 = 35  5 * 8 = 40  5 * 9 = 45  
6 * 1 = 6  6 * 2 = 12  6 * 3 = 18  6 * 4 = 24  6 * 5 = 30  6 * 6 = 36  6 * 7 = 42  6 * 8 = 48  6 * 9 = 54  
7 * 1 = 7  7 * 2 = 14  7 * 3 = 21  7 * 4 = 28  7 * 5 = 35  7 * 6 = 42  7 * 7 = 49  7 * 8 = 56  7 * 9 = 63  
8 * 1 = 8  8 * 2 = 16  8 * 3 = 24  8 * 4 = 32  8 * 5 = 40  8 * 6 = 48  8 * 7 = 56  8 * 8 = 64  8 * 9 = 72  
9 * 1 = 9  9 * 2 = 18  9 * 3 = 27  9 * 4 = 36  9 * 5 = 45  9 * 6 = 54  9 * 7 = 63  9 * 8 = 72  9 * 9 = 81  


In [ ]:
i <- 1
while (i <= 4) {
    print(i)
    i = i+1
}

[1] 1
[1] 2
[1] 3
[1] 4


In [ ]:
sum <- 0
i <- 1

while (i <= 10) {
    sum = sum + i
    i = i+1
}
print(sum)

[1] 55


In [ ]:
x <- c(70, 60, 55, 95, 80, 70, 85, 47, 83, 78)
sum = 0
avg = 0

for (i in 1:10) {
    sum = sum + x[i]
    i = i+1
}
avg = sum/10
cat("평균은 ", avg, "입니다.")

평균은  72.3 입니다.

In [ ]:
x <- c(70, 60, 55, 95, 80, 70, 85, 47, 83, 78)
sum = 0
avg = 0

i <- 1
while (i <= 10) {
    sum = sum + x[i]
    i = i+1
}
avg = sum/10
cat("평균은 ", avg, "입니다.")

평균은  72.3 입니다.

>>>**06 함수와 라이브러리(모듈, 패키지)**

In [ ]:
sum <- function(x, y){      # sum은 함수이름, x,y는 매개변수
    return(x+y)             # 함수가 호출되면 x,y 2개의 값을 더한 결과를 반환
}

In [ ]:
f1 <- function(x){
    if(x %/% 2 == 0) {      # 2로 나눈 나머지가 0이면(짝수이면)
        return("짝수")      # "짝수"를 반환
    }else{
        return("홀수")      # "홀수"를 반환
    }
}

f1(12)                      # 12를 인수로 함수 f1 호출

[1] "홀수"

In [ ]:
f2 <- function(x, y){
    return(x*y)
}

f2(2,8)                     # 2, 8을 인수로 함수 f2 호출

[1] 16